apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: apz712oo9-nodejs 
  janus-idp.io/tekton: apz712oo9-nodejs
  backstage.io/kubernetes-id: apz712oo9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: apz712oo9-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  